# Server port
server.port=${PORT:8080}

# Database Configuration (Persistent H2 in local file)
spring.datasource.url=jdbc:h2:file:./data/beachtennis;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Allow H2 console in frames
spring.headers.frame-options=sameorigin
